-- MySQL Script generated by MySQL Workbench
-- 04/21/16 10:48:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema venda_direta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema venda_direta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venda_direta` DEFAULT CHARACTER SET utf8 ;
USE `venda_direta` ;

-- -----------------------------------------------------
-- Table `venda_direta`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`categoria` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`estado` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Estado` VARCHAR(50) NOT NULL,
  `Sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`cidade` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Cidade` VARCHAR(50) NOT NULL,
  `Código_Estado` INT(11) NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `FK_2jmxjcmevkwgq1ie4uo9t39ap` (`Código_Estado` ASC),
  CONSTRAINT `FK_2jmxjcmevkwgq1ie4uo9t39ap`
    FOREIGN KEY (`Código_Estado`)
    REFERENCES `venda_direta`.`estado` (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`cliente` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(14) NOT NULL,
  `Endereço` VARCHAR(100) NOT NULL,
  `Nome_Cliente` VARCHAR(100) NOT NULL,
  `RG` VARCHAR(12) NOT NULL,
  `Telefone` VARCHAR(14) NOT NULL,
  `Código_Cidade` INT(11) NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `FK_k1dij2p6j3m1csm5cywxeoh56` (`Código_Cidade` ASC),
  CONSTRAINT `FK_k1dij2p6j3m1csm5cywxeoh56`
    FOREIGN KEY (`Código_Cidade`)
    REFERENCES `venda_direta`.`cidade` (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`formapagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`formapagamento` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `Entrada` TINYINT(4) NOT NULL,
  `Parcelas` TINYINT(4) NOT NULL,
  `Tipo_Pagamento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`fornecedor` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `Endereço` VARCHAR(100) NOT NULL,
  `Nome_Fornecedor` VARCHAR(100) NOT NULL,
  `Telefone` VARCHAR(14) NOT NULL,
  `Tipo_Fornecedor` VARCHAR(100) NOT NULL,
  `Código_Cidade` INT(11) NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `FK_j6g8q6rr5mc55avyv6q5hirne` (`Código_Cidade` ASC),
  CONSTRAINT `FK_j6g8q6rr5mc55avyv6q5hirne`
    FOREIGN KEY (`Código_Cidade`)
    REFERENCES `venda_direta`.`cidade` (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`marca` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome_Marca` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`pedido` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `Data_do_Pedito` DATE NOT NULL,
  `Prazo_de_Pagamento` DATE NOT NULL,
  `Código_Cliente` INT(11) NOT NULL,
  `Código_Forma_Pagamento` INT(11) NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `FK_j3yuex2vo8oxdmlg2yx2x1wu` (`Código_Cliente` ASC),
  INDEX `FK_c3yiu0hk0nj2nlyxrly8359ca` (`Código_Forma_Pagamento` ASC),
  CONSTRAINT `FK_c3yiu0hk0nj2nlyxrly8359ca`
    FOREIGN KEY (`Código_Forma_Pagamento`)
    REFERENCES `venda_direta`.`formapagamento` (`Código`),
  CONSTRAINT `FK_j3yuex2vo8oxdmlg2yx2x1wu`
    FOREIGN KEY (`Código_Cliente`)
    REFERENCES `venda_direta`.`cliente` (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`produto` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `Estoque` SMALLINT(6) NOT NULL,
  `Estoque_Minimo` SMALLINT(6) NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Valor_de_Compra` DECIMAL(6,2) NOT NULL,
  `Valor_de_Venda` DECIMAL(6,2) NOT NULL,
  `Código_Categoria` INT(11) NOT NULL,
  `Código_Fornecedor` INT(11) NOT NULL,
  `Código_Marca` INT(11) NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `FK_cp6oyec4a15byonh3syoyrbs1` (`Código_Categoria` ASC),
  INDEX `FK_9shd4ewyj92dyk19hlblx842` (`Código_Fornecedor` ASC),
  INDEX `FK_8s8x049lbxo74bmu7c2k0paqi` (`Código_Marca` ASC),
  CONSTRAINT `FK_8s8x049lbxo74bmu7c2k0paqi`
    FOREIGN KEY (`Código_Marca`)
    REFERENCES `venda_direta`.`marca` (`Código`),
  CONSTRAINT `FK_9shd4ewyj92dyk19hlblx842`
    FOREIGN KEY (`Código_Fornecedor`)
    REFERENCES `venda_direta`.`fornecedor` (`Código`),
  CONSTRAINT `FK_cp6oyec4a15byonh3syoyrbs1`
    FOREIGN KEY (`Código_Categoria`)
    REFERENCES `venda_direta`.`categoria` (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`produtopedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`produtopedido` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `Quantidade_Produto` SMALLINT(6) NOT NULL,
  `Código_Pedito` INT(11) NOT NULL,
  `Código_Produto` INT(11) NOT NULL,
  PRIMARY KEY (`Código`),
  INDEX `FK_gcofmikxeyra8grls24p8t5jt` (`Código_Pedito` ASC),
  INDEX `FK_16i4ipdo4vci9puglp5vrj42g` (`Código_Produto` ASC),
  CONSTRAINT `FK_16i4ipdo4vci9puglp5vrj42g`
    FOREIGN KEY (`Código_Produto`)
    REFERENCES `venda_direta`.`produto` (`Código`),
  CONSTRAINT `FK_gcofmikxeyra8grls24p8t5jt`
    FOREIGN KEY (`Código_Pedito`)
    REFERENCES `venda_direta`.`pedido` (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `venda_direta`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_direta`.`usuario` (
  `Código` INT(11) NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(14) NULL DEFAULT NULL,
  `Usuário` VARCHAR(50) NOT NULL,
  `Senha` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
